project:
  type: website
website:
  title: "Degrees of Change: Navigating Temperature Variability"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Sources
        menu:
          - href: source-1.qmd
            text: Source 1
          - href: source-2.qmd
            text: Source 2 
      - about.qmd
      - login/signup.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



